"""
@leetcode-389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""

def findTheDifference(s,t):
        diki={}
        for i in s:
            if i in diki:
                diki[i]+=1
            else:
                diki[i]=1
        dik={}
        for i in t:
            if i in dik:
                dik[i]+=1
            else:
                dik[i]=1
        for i in dik:
            if dik[i]!=diki.get(i,0):
                return i
s,t=input().split()
print(findTheDifference(s,t))